name: CD

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write 

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Labels
        id: check_labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name.toLowerCase());
            if (labels.includes('bump:major')) return core.setOutput('level', 'major');
            if (labels.includes('bump:minor')) return core.setOutput('level', 'minor');
            if (labels.includes('bump:patch')) return core.setOutput('level', 'patch');
            return core.setOutput('level', 'none');
      - name: Bump & Push
        if: steps.check_labels.outputs.level != 'none'
        run: |
          pip install bumpver build
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          bumpver update --${{ steps.check_labels.outputs.level }} --commit --tag-num --push
        shell: bash
      - name: Publish ðŸ“¦
        if: steps.check_labels.outputs.level != 'none'
        uses: pypa/gh-action-pypi-publish@release/v1
